#! /usr/bin/env bash

#
# This script is a "front end" to the helm binary. You'll
# typically install it as "helm" in some directory that will
# be called before where the helm binary is in the PATH.
#

# Edit this file to point to where you
# installed the helm-wrapper.py script
# I assume the set-up of KK lab with these defaults:

# For remote debugging, uncomment the next line
# note that you may need to edit .vscode/launch.json
# for your configuration to work.
# export DEBUG_WRAPPER=1

# Edit this to match the install location
# as done in hwsettings.py:
WRAPPER_INSTALL_DIR=/usr/local/sbin

# Get the modified command from Python script
MODIFIED_CMD=$(python3 "$WRAPPER_INSTALL_DIR/helm_wrap.py" "$@")

if [ $? -eq 0 ]; then
  #echo "Executing: $MODIFIED_CMD"
  
  # Execute the correct Helm command
  eval "$MODIFIED_CMD"
else
  echo "Helm command failed to parse"
  exit 1
fi